### ISSUE TITLE
The pose estimation seems perform bad 

### ISSUE THREAD

**Issue by deep-practice** [GajuuzZ/Human-Falling-Detect-Tracks#1]

**Comment by deep-practice** [comment]
Thanks for providing the pipeline,it's a good start for me to work on action recognition.

**Comment by GajuuzZ** [comment]
My pleasure. Yep, the pose model is pre-trained from original Alpha-Pose. As my experimented the Alpha-Pose is the best perform on estimate the pose when human is falling or lying down compare to other model like OpenPose.

**Comment by deep-practice** [comment]
Sometimes,there are some weird joints pair,for example,one person's joint is connected to another person's joint.Actually,they are far away from each other.Due to the wrong connection,the program will  recognize the action as lying down or falling down.So do you know how to impove the performance?

**Comment by GajuuzZ** [comment]
Actually, Alpha-Pose is a single pose estimation. It need two process detection from object-detection model like YOLO and then use cropped image from that detected to the pose model. So that weird joints you seen it the same person. Even it weird joints it has a low score so i use these score to lower the predicted score too. Or you can train the pose model more with a rotation joints and image for more precision.
