### ISSUE TITLE
Why using two detection networks?

### ISSUE THREAD

**Issue by mufenzhimi** [GajuuzZ/Human-Falling-Detect-Tracks#68]
Hi, your project really shadows a light on how to design a light pipeline of st-gcn based recognization! Thanks a lot. And it achieve great results when I am using my own datasets.
Only one thing that I am really curious about is that why you train a new tiny-yolo yourself as there is already a detection network in alphapose? Sometimes I'll see two bbbox when there is only one person there. Looking forword to your reply.

**Comment by GajuuzZ** [comment]
Thanks for your compliment, First I've trained a new Tiny-Yolo with one class because I want to detect only humans and reduce the size of the model as much as possible. In Alphapose just the pose model only is not an end-to-end model there is no detection it's a single pose model. And the two bbox you saw is a trick I use a Kalman filter to predict the next position of the bbox in case the detection model can't detect continually. (especially when fall)

**Comment by mufenzhimi** [comment]
I got it. Thanks for your quick reply and detailed explanation.
